---
- name: install custom facts
  hosts: ansible03.example.com
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: localfacts.fact
  tasks:
    - name: create fact directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: install new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"

- name: install and start
  hosts: ansible03.example.com
  tasks:
    - name: install 
      yum:
        name: "{{ ansible_local.localfacts.localfacts.package }}"
    - name: start 
      service:
        name: "{{ ansible_local.localfacts.localfacts.service }}"
        state: started
