---
- name: test ftp upload
  hosts: localhost
  tasks:
  - name: install lftp
    yum:
      name: lftp
  - name: upload file
    shell: >
      lftp ansible02.example.com <<EOF
      cd pub
      put /etc/test
      EOF
